---
- name: default configuration generic
  block:
  - name: Wait for cloud-init to complete
    shell: journalctl --boot | grep 'Cloud-init.*finished at'
    register: cloud_init_install
    retries: 60
    delay: 5
    until: cloud_init_install is success

  - name: add this plays
    debug:
      msg: "{{ lookup( 'fileglob', '*.yml' ).split(',') | reject('search', 'main.yml') | sort }}"

  - name: Add and run all plays
    include_tasks: "{{ element }}"
    with_items: "{{ lookup( 'fileglob', '*.yml' ).split(',') | reject('search', 'main.yml') | sort }}"
    loop_control:
      loop_var: element
...
